package com.ctre.phoenix.MotorControl.CAN;
import com.ctre.phoenix.MotorControl.CAN.MotControllerJNI;
import com.ctre.phoenix.MotorControl.IMotorController;
import com.ctre.phoenix.MotorControl.ControlMode;
import com.ctre.phoenix.MotorControl.ControlFrame;
import com.ctre.phoenix.MotorControl.VelocityMeasPeriod;
import com.ctre.phoenix.MotorControl.NeutralMode;
import com.ctre.phoenix.MotorControl.LimitSwitchSource;
import com.ctre.phoenix.MotorControl.RemoteLimitSwitchSource;
import com.ctre.phoenix.MotorControl.LimitSwitchNormal;
import com.ctre.phoenix.MotorControl.FeedbackDevice;
import com.ctre.phoenix.MotorControl.StatusFrame;
import com.ctre.phoenix.MotorControl.StatusFrameEnhanced;
import com.ctre.phoenix.MotorControl.RemoteFeedbackDevice;
import com.ctre.phoenix.MotorControl.ParamEnum;
import com.ctre.phoenix.ErrorCode;

public class BaseMotorController implements com.ctre.phoenix.MotorControl.IMotorController {
	
	private ErrorCode _lastError = ErrorCode.OKAY;
	private ControlMode m_controlMode = ControlMode.PercentOutput;
	private ControlMode m_sendMode = ControlMode.PercentOutput;
	
	private int _arbId = 0;
	private float m_setPoint = 0;
	private boolean _invert = false;
	private int m_profile = 0;
	
	protected long m_handle;
	
	/**
	 * Constructor for motor controllers.
	 */
	BaseMotorController(int arbId)
	{
		m_handle = MotControllerJNI.Create(arbId);
		_arbId = arbId;
	}
	
  /**
   * Returns the Device ID
   *
   * @return  Device number.   */
	public int getDeviceID()
	{
		return MotControllerJNI.GetDeviceNumber(m_handle);
	}
	
	protected long getHandle()
	{
		return m_handle;
	}
	
	/**
	 * Sets the appropriate output on the talon, depending on the mode.
	 *
	 * In PercentOutput, the output is between -1.0 and 1.0, with 0.0 as stopped.
	 * In Voltage mode, output value is in volts.
	 * In Current mode, output value is in amperes.
	 * In Speed mode, output value is in position change / 100ms.
	 * In Position mode, output value is in encoder ticks or an analog value,
	 *   depending on the sensor.
	 * In Follower mode, the output value is the integer device ID of the talon to
	 * duplicate.
	 *
	 * @param outputValue The setpoint value, as described above.
	 * @see #SelectProfileSlot to choose between the two sets of gains.
	 */
	public void set(ControlMode mode, float outputValue)
	{
		set(mode, outputValue, 0);
	}
	
	public void set(ControlMode mode, float demand0, float demand1)
	{
		m_controlMode = mode;
		m_sendMode = mode;
		m_setPoint = demand0;
		
		switch(m_controlMode)
		{
			case PercentOutput:
			case TimedPercentOutput:
				MotControllerJNI.SetDemand(m_handle, m_sendMode.value,(int)(1023 * demand0), 0);
				break;
			case Follower:
				MotControllerJNI.SetDemand(m_handle, m_sendMode.value, (int)demand0, 0);
				break;
			default:
				MotControllerJNI.SetDemand(m_handle, m_sendMode.value, 0, 0);
		}
		
	}
	
	public void neutralOutput()
	{
		set(ControlMode.Disabled, 0);
	}
	
  /**
   * Sets the mode of operation during neutral throttle output.
   *
   * @param neutralMode The desired mode of operation when the Controller output throttle is neutral (ie brake/coast)
   **/
	public void setNeutralMode(NeutralMode neutralMode)
	{
		MotControllerJNI.SetNeutralMode(m_handle, neutralMode.value);
	}
  /**
   * Sets the phase of the sensor.  Use when controller forward/reverse output doesn't 
correlate to appropriate forward/reverse reading of sensor.
   *
   * @param PhaseSensor Indicates whether to invert the phase of the sensor.
   **/
	public void setSensorPhase(boolean PhaseSensor)
	{
		MotControllerJNI.SetSensorPhase(m_handle, PhaseSensor);
	}
  /**
   * Inverts the output of the motor controller.  LEDs, sensor phase,
and limit switches will also be inverted to match the new 
forward/reverse directions.
   *
   * @param invert Invert state to set.
   **/
	public void setInverted(boolean invert)
	{
		_invert = invert; /* cache for getter */
		MotControllerJNI.SetInverted(m_handle, invert);
	}
	
	public boolean getInverted()
	{
		return _invert;
	}
  /**
   * Configures the open-loop ramp rate of throttle output.
   *
   * @param secondsFromNeutralToFull Minimum desired time to go from neutral to full throttle.  A value of '0' will disable the ramp.
   * @param timeoutMs                Timeout value in ms.  Function will generate error if config is not successful within timeout.
   * @return                         Error Code generated by function.  0 indicates no error.   */
	public int configOpenLoopRamp(float secondsFromNeutralToFull, int timeoutMs)
	{
		return MotControllerJNI.ConfigOpenLoopRamp(m_handle, secondsFromNeutralToFull, timeoutMs);
	}
  /**
   * Configures the closed-loop ramp rate of throttle output.
   *
   * @param secondsFromNeutralToFull Minimum desired time to go from neutral to full throttle.  A value of '0' will disable the ramp.
   * @param timeoutMs                Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return                          Error Code generated by function.  0 indicates no error.   */
	public int configClosedLoopRamp(float secondsFromNeutralToFull, int timeoutMs)
	{
		return MotControllerJNI.ConfigClosedLoopRamp(m_handle, secondsFromNeutralToFull, timeoutMs);
	}
  /**
   * Configures the forward peak output percentage.
   *
   * @param percentOut Desired peak output percentage.
   * @param timeoutMs  Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return            Error Code generated by function.  0 indicates no error.   */
	public int configPeakOutputForward(float percentOut, int timeoutMs)
	{
		return MotControllerJNI.ConfigPeakOutputForward(m_handle, percentOut, timeoutMs);
	}
  /**
   * Configures the reverse peak output percentage.
   *
   * @param percentOut Desired peak output percentage.
   * @param timeoutMs  Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return            Error Code generated by function.  0 indicates no error.   */
	public int configPeakOutputReverse(float percentOut, int timeoutMs)
	{
		return MotControllerJNI.ConfigPeakOutputReverse(m_handle, percentOut, timeoutMs);
	}
  /**
   * Configures the forward nominal output percentage.
   *
   * @param percentOut Nominal (minimum) percent output.
   * @param timeoutMs  Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return            Error Code generated by function.  0 indicates no error.   */
	public int configNominalOutputForward(float percentOut, int timeoutMs)
	{
		return MotControllerJNI.ConfigNominalOutputForward(m_handle, percentOut, timeoutMs);
	}
  /**
   * Configures the reverse nominal output percentage.
   *
   * @param percentOut Nominal (minimum) percent output.
   * @param timeoutMs  Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return            Error Code generated by function.  0 indicates no error.   */
	public int configNominalOutputReverse(float percentOut, int timeoutMs)
	{
		return MotControllerJNI.ConfigNominalOutputReverse(m_handle, percentOut, timeoutMs);
	}
  /**
   * Configures the output deadband percentage.
   *
   * @param percentDeadband Desired deadband percentage.  Minimum is 0.1%, Maximum is 12.5%.
   * @param timeoutMs       Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return                 Error Code generated by function.  0 indicates no error.   */
	public int configNeutralDeadband(float percentDeadband, int timeoutMs)
	{
		return MotControllerJNI.ConfigNeutralDeadband(m_handle, percentDeadband, timeoutMs);
	}
  /**
   * Configures the Voltage Compensation saturation voltage.
   *
   * @param voltage    TO-DO: Comment me!
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Error Code generated by function.  0 indicates no error.   */
	int ConfigVoltageCompSaturation(float voltage, int timeoutMs)
	{
		return MotControllerJNI.ConfigVoltageCompSaturation(m_handle, voltage, timeoutMs);
	}
  /**
   * Configures the voltage measurement filter.
   *
   * @param filterWindowSamples Number of samples in the rolling average of voltage measurement.
   * @param timeoutMs           Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return                     Error Code generated by function.  0 indicates no error.   */
	public int configVoltageMeasurementFilter(int filterWindowSamples, int timeoutMs)
	{
		return MotControllerJNI.ConfigVoltageMeasurementFilter(m_handle, filterWindowSamples, timeoutMs);
	}
  /**
   * Enables voltage compensation.  If enabled, voltage compensation works in all control modes.
   *
   * @param enable Enable state of voltage compensation.
   **/
	public void enableVoltageCompensation(boolean enable)
	{
		MotControllerJNI.EnableVoltageCompensation(m_handle, enable);
	}
  /**
   * Gets the bus voltage seen by the motor controller.
   *
   * @return        The bus voltage value (in volts).   */
	public float getBusVoltage()
	{
		return MotControllerJNI.GetBusVoltage(m_handle);
	}
  /**
   * Gets the output percentage of the motor controller.
   *
   * @return              Output of the motor controller (in percent).   */
	public float getMotorOutputPercent()
	{
		return MotControllerJNI.GetMotorOutputPercent(m_handle);
	}
	
	public float getMotorOutputVoltage()
	{
		float v = getBusVoltage();
		float p = getMotorOutputPercent();
		return v * p;
	}
	
  /**
   * Gets the output current of the motor controller.
   *
   * @return        The output current (in amps).   */
	public float getOutputCurrent()
	{
		return MotControllerJNI.GetOutputCurrent(m_handle);
	}
  /**
   * Gets the temperature of the motor controller.
   *
   * @return            Temperature of the motor controller (in °C)   */
	public float getTemperature()
	{
		return MotControllerJNI.GetTemperature(m_handle);
	}

	/**
	   * Select the remote feedback device for the motor controller.
	   *
	   * @param feedbackDevice Remote Feedback Device to select.
	   * @param timeoutMs      Timeout value in ms.  @see #ConfigOpenLoopRamp
	   * @return                Error Code generated by function.  0 indicates no error.   */
	int ConfigSelectedFeedbackSensor(RemoteFeedbackDevice feedbackDevice, int timeoutMs)
	{
		int e1 = MotControllerJNI.ConfigRemoteFeedbackFilter(m_handle, feedbackDevice._arbId, feedbackDevice._peripheralIndex, feedbackDevice._reserved, timeoutMs);
		int e2 = MotControllerJNI.ConfigSelectedFeedbackSensor(m_handle, FeedbackDevice.RemoteSensor.value, timeoutMs);
		
		if(e1 == ErrorCode.OKAY.value)
			return e2;
		else
			return e1;
	}
	
  /**
   * Select the feedback device for the motor controller.
   *
   * @param feedbackDevice Feedback Device to select.
   * @param timeoutMs      Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return                Error Code generated by function.  0 indicates no error.   */
	int ConfigSelectedFeedbackSensor(FeedbackDevice feedbackDevice, int timeoutMs)
	{
		return MotControllerJNI.ConfigSelectedFeedbackSensor(m_handle, feedbackDevice.value, timeoutMs);
	}
  /**
   * Get the selected sensor position.
   *
   * @return      Position of selected sensor (in Raw Sensor Units).   */
	public int GetSelectedSensorPosition()
	{
		return MotControllerJNI.GetSelectedSensorPosition(m_handle);
	}
  /**
   * Get the selected sensor velocity.
   *
   * @return      Velocity of selected sensor (in Raw Sensor Units per 100 ms).   */
	public int GetSelectedSensorVelocity(int param)
	{
		return MotControllerJNI.GetSelectedSensorVelocity(m_handle);
	}
  /**
   * Sets the sensor position to the given value.
   *
   * @param sensorPos Position to set for the selected sensor (in Raw Sensor Units).
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Error Code generated by function.  0 indicates no error.   */
	public int SetSelectedSensorPosition(int sensorPos, int timeoutMs)
	{
		return MotControllerJNI.SetSelectedSensorPosition(m_handle, sensorPos, timeoutMs);
	}
  /**
   * Sets the period of the given control frame.
   *
   * @param frame    Frame whose period is to be changed.
   * @param periodMs Period in ms for the given frame.
   * @return          Error Code generated by function.  0 indicates no error.   */
	public int SetControlFramePeriod(ControlFrame frame, int periodMs)
	{
		return MotControllerJNI.SetControlFramePeriod(m_handle, frame.value, periodMs);
	}
  /**
   * Sets the period of the given status frame.
   *
   * @param frame     Frame whose period is to be changed.
   * @param periodMs  Period in ms for the given frame.
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Error Code generated by function.  0 indicates no error.   */
	public int SetStatusFramePeriod(StatusFrame frame, int periodMs, int timeoutMs)
	{
		return MotControllerJNI.SetStatusFramePeriod(m_handle, frame.value, periodMs, timeoutMs);
	}
  /**
   * Gets the period of the given status frame.
   *
   * @param frame     Frame to get the period of.
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return          Period of the given status frame.   */
	public int GetStatusFramePeriod(StatusFrame frame, int timeoutMs)
	{
		return MotControllerJNI.GetStatusFramePeriod(m_handle, frame.value, timeoutMs);
	}
	/**
	   * Gets the period of the given status frame.
	   *
	   * @param frame     Frame to get the period of.
	   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
	   * @return          Period of the given status frame.   */
		public int GetStatusFramePeriod(StatusFrameEnhanced frame, int timeoutMs)
		{
			return MotControllerJNI.GetStatusFramePeriod(m_handle, frame.value, timeoutMs);
		}
  /**
   * Sets the period over which velocity measurements are taken.
   *
   * @param period    Desired period for the velocity measurement. @see #VelocityMeasPeriod
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Error Code generated by function.  0 indicates no error.   */
	public int ConfigVelocityMeasurementPeriod(VelocityMeasPeriod period, int timeoutMs)
	{
		return MotControllerJNI.ConfigVelocityMeasurementPeriod(m_handle, period.value, timeoutMs);
	}
  /**
   * Sets the number of velocity samples used in the rolling average velocity measurement.
   *
   * @param windowSize Number of samples in the rolling average of velocity measurement.
   * @param timeoutMs  Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return            Error Code generated by function.  0 indicates no error.   */
	public int ConfigVelocityMeasurementWindow(int windowSize, int timeoutMs)
	{
		return MotControllerJNI.ConfigVelocityMeasurementWindow(m_handle, windowSize, timeoutMs);
	}
  /**
   * Configures the forward limit switch for a remote source.
   *
   * @param type              Remote limit switch source. @see #LimitSwitchSource
   * @param normalOpenOrClose Setting for normally open or normally closed.
   * @param deviceID          Device ID of remote source.
   * @param timeoutMs         Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return                   Error Code generated by function.  0 indicates no error.   */
	public int ConfigForwardLimitSwitchSource(RemoteLimitSwitchSource type, LimitSwitchNormal normalOpenOrClose, int deviceID, int timeoutMs)
	{
		return MotControllerJNI.ConfigForwardLimitSwitchSource(m_handle, type.value, normalOpenOrClose.value, deviceID, timeoutMs);
	}
  /**
   * Configures the reverse limit switch for a remote source.
   *
   * @param type              Remote limit switch source. @see #LimitSwitchSource
   * @param normalOpenOrClose Setting for normally open or normally closed.
   * @param deviceID          Device ID of remote source.
   * @param timeoutMs         Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return                   Error Code generated by function.  0 indicates no error.   */
	public int ConfigReverseLimitSwitchSource(RemoteLimitSwitchSource type, LimitSwitchNormal normalOpenOrClose, int deviceID, int timeoutMs)
	{
		return MotControllerJNI.ConfigReverseLimitSwitchSource(m_handle, type.value, normalOpenOrClose.value, deviceID, timeoutMs);
	}
  /**
   * Sets the enable state for limit switches.
   *
   * @param enable Enable state for limit switches.
   **/
	public void EnableLimitSwitches(boolean enable)
	{
		MotControllerJNI.EnableLimitSwitches(m_handle, enable);
	}
  /**
   * Configures the forward soft limit.
   *
   * @param forwardSensorLimit Forward Sensor Position Limit (in Raw Sensor Units).
   * @param timeoutMs          Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return                    Error Code generated by function.  0 indicates no error.   */
	public int ConfigForwardSoftLimit(int forwardSensorLimit, int timeoutMs)
	{
		return MotControllerJNI.ConfigForwardSoftLimit(m_handle, forwardSensorLimit, timeoutMs);
	}
  /**
   * Configures the reverse soft limit.
   *
   * @param reverseSensorLimit Reverse Sensor Position Limit (in Raw Sensor Units).
   * @param timeoutMs          Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return                    Error Code generated by function.  0 indicates no error.   */
	public int ConfigReverseSoftLimit(int reverseSensorLimit, int timeoutMs)
	{
		return MotControllerJNI.ConfigReverseSoftLimit(m_handle, reverseSensorLimit, timeoutMs);
	}
  /**
   * Sets the enable state for soft limit switches.
   *
   * @param enable Enable state for soft limit switches.
   **/
	public void EnableSoftLimits(boolean enable)
	{
		MotControllerJNI.EnableSoftLimits(m_handle, enable);
	}
  /**
   * Sets the 'P' constant in the given parameter slot.
   *
   * @param slotIdx   Parameter slot for the constant.
   * @param value     Value of the P constant.
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Error Code generated by function.  0 indicates no error.   */
	public int Config_kP(int slotIdx, float value, int timeoutMs)
	{
		return MotControllerJNI.Config_kP(m_handle, slotIdx, value, timeoutMs);
	}
  /**
   * Sets the 'I' constant in the given parameter slot.
   *
   * @param slotIdx   Parameter slot for the constant.
   * @param value     Value of the I constant.
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Error Code generated by function.  0 indicates no error.   */
	public int Config_kI(int slotIdx, float value, int timeoutMs)
	{
		return MotControllerJNI.Config_kI(m_handle, slotIdx, value, timeoutMs);
	}
  /**
   * Sets the 'D' constant in the given parameter slot.
   *
   * @param slotIdx   Parameter slot for the constant.
   * @param value     Value of the D constant.
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Error Code generated by function.  0 indicates no error.   */
	public int Config_kD(int slotIdx, float value, int timeoutMs)
	{
		return MotControllerJNI.Config_kD(m_handle, slotIdx, value, timeoutMs);
	}
  /**
   * Sets the 'F' constant in the given parameter slot.
   *
   * @param slotIdx   Parameter slot for the constant.
   * @param value     Value of the F constant.
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Error Code generated by function.  0 indicates no error.   */
	public int Config_kF(int slotIdx, float value, int timeoutMs)
	{
		return MotControllerJNI.Config_kF(m_handle, slotIdx, value, timeoutMs);
	}
  /**
   * Sets the Integral Zone constant in the given parameter slot.
   *
   * @param slotIdx   Parameter slot for the constant.
   * @param izone     Value of the Integral Zone constant.
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Error Code generated by function.  0 indicates no error.   */
	public int Config_IntegralZone(int slotIdx, float izone, int timeoutMs)
	{
		return MotControllerJNI.Config_IntegralZone(m_handle, slotIdx, izone, timeoutMs);
	}
  /**
   * Sets the allowable closed-loop error in the given parameter slot.
   *
   * @param slotIdx                  Parameter slot for the constant.
   * @param allowableClosedLoopError Value of the allowable closed-loop error.
   * @param timeoutMs                Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return                          Error Code generated by function.  0 indicates no error.   */
	public int ConfigAllowableClosedloopError(int slotIdx, int allowableClosedLoopError, int timeoutMs)
	{
		return MotControllerJNI.ConfigAllowableClosedloopError(m_handle, slotIdx, allowableClosedLoopError, timeoutMs);
	}
  /**
   * Sets the maximum integral accumulator in the given parameter slot.
   *
   * @param slotIdx   Parameter slot for the constant.
   * @param iaccum    Value of the maximum integral accumulator.
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Error Code generated by function.  0 indicates no error.   */
	public int ConfigMaxIntegralAccumulator(int slotIdx, float iaccum, int timeoutMs)
	{
		return MotControllerJNI.ConfigMaxIntegralAccumulator(m_handle, slotIdx, iaccum, timeoutMs);
	}
  /**
   * Sets the integral accumulator.
   *
   * @param iaccum    Value to set for the integral accumulator.
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Error Code generated by function.  0 indicates no error.   */
	public int SetIntegralAccumulator(float iaccum, int timeoutMs)
	{
		return MotControllerJNI.SetIntegralAccumulator(m_handle, iaccum, timeoutMs);
	}
  /**
   * Gets the closed-loop error.
   *
   * @param slotIdx         Parameter slot of the constant.
   * @return                Closed-loop error value.   */
	int GetClosedLoopError(int slotIdx)
	{
		return MotControllerJNI.GetClosedLoopError(m_handle, slotIdx);
	}
  /**
   * Gets the iaccum value.
   *
   * @param slotIdx Parameter slot of the constant.
   * @return        Integral accumulator value.   */
	public float GetIntegralAccumulator(int slotIdx)
	{
		return MotControllerJNI.GetIntegralAccumulator(m_handle, slotIdx);
	}
  /**
   * Gets the derivative of the closed-loop error.
   *
   * @param slotIdx Parameter slot of the constant.
   * @return        The error derivative value.   */
	public float GetErrorDerivative(int slotIdx)
	{
		return MotControllerJNI.GetErrorDerivative(m_handle, slotIdx);
	}
  /**
   * Selects which profile slot to use for closed-loop control.
   *
   * @param slotIdx Profile slot to select.
   **/
	public void SelectProfileSlot(int slotIdx)
	{
		m_profile = slotIdx;
		MotControllerJNI.SelectProfileSlot(m_handle, slotIdx);
	}
  /**
   * Sets the Motion Magic Cruise Velocity.
   *
   * @param sensorUnitsPer100ms Motion Magic Cruise Velocity (in Raw Sensor Units per 100 ms).
   * @param timeoutMs           Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return                     Error Code generated by function.  0 indicates no error.   */
	public int ConfigMotionCruiseVelocity(int sensorUnitsPer100ms, int timeoutMs)
	{
		return MotControllerJNI.ConfigMotionCruiseVelocity(m_handle, sensorUnitsPer100ms, timeoutMs);
	}
  /**
   * Sets the Motion Magic Acceleration.
   *
   * @param sensorUnitsPer100msPerSec Motion Magic Acceleration (in Raw Sensor Units per 100 ms per second).
   * @param timeoutMs                 Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return                           Error Code generated by function.  0 indicates no error.   */
	public int ConfigMotionAcceleration(int sensorUnitsPer100msPerSec, int timeoutMs)
	{
		return MotControllerJNI.ConfigMotionAcceleration(m_handle, sensorUnitsPer100msPerSec, timeoutMs);
	}
  /**
   * Gets the last error generated by this object.
   *
   * @return  Last Error Code generated by a function.   */
	public int GetLastError()
	{
		return MotControllerJNI.GetLastError(m_handle);
	}
	
	//TO-DO: Set Last Error
	
	//TO-DO: Get Faults & Get/Clear Sticky Faults
	
  /**
   * Gets the firmware version of the device.
   *
   * @return  Firmware version of device.   */
	public int GetFirmwareVersion()
	{
		return MotControllerJNI.GetFirmwareVersion(m_handle);
	}
  /**
   * Returns true if the device has reset.
   *
   * @return  Has a Device Reset Occurred?   */
	public boolean HasResetOccurred()
	{
		return MotControllerJNI.HasResetOccurred(m_handle);
	}
  /**
   * Sets the value of a custom parameter.
   *
   * @param newValue   Value for custom parameter.
   * @param paramIndex Index of custom parameter.
   * @param timeoutMs  Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return            Error Code generated by function.  0 indicates no error.   */
	public int ConfigSetCustomParam(int newValue, int paramIndex, int timeoutMs)
	{
		return MotControllerJNI.ConfigSetCustomParam(m_handle, newValue, paramIndex, timeoutMs);
	}
  /**
   * Gets the value of a custom parameter.
   *
   * @param paramIndex Index of custom parameter.
   * @param timoutMs   Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Value of the custom param.  */
	public int ConfigGetCustomParam(int paramIndex, int timoutMs)
	{
		return MotControllerJNI.ConfigGetCustomParam(m_handle, paramIndex, timoutMs);
	}
  /**
   * Sets a parameter.
   *
   * @param param     Parameter enumeration.
   * @param value     Value of parameter.
   * @param subValue  Subvalue for parameter.  Maximum value of 255.
   * @param ordinal   Ordinal of parameter.
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return           Error Code generated by function.  0 indicates no error.   */
	public int ConfigSetParameter(ParamEnum param, float value, int subValue, int ordinal, int timeoutMs)
	{
		return MotControllerJNI.ConfigSetParameter(m_handle, param.value, value, subValue, ordinal, timeoutMs);
	}
  /**
   * Gets a parameter.
   *
   * @param param     Parameter enumeration.
   * @param ordinal   Ordinal of parameter.
   * @param timeoutMs Timeout value in ms.  @see #ConfigOpenLoopRamp
   * @return          Value of parameter.  */
	public float ConfigGetParameter(ParamEnum param, int ordinal, int timeoutMs)
	{
		return MotControllerJNI.ConfigGetParameter(m_handle, param.value, ordinal, timeoutMs);
	}
	
	
	public int getBaseID()
	{
		return _arbId;
	}
	
	
	public void follow(IMotorController masterToFollow)
	{
		int devId = masterToFollow.getDeviceID();
		set(ControlMode.Follower, devId);
	}
	public void valueUpdated()
	{
		
	}
}