/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctre_phoenix_Sensors_PigeonImuJNI */

#ifndef _Included_com_ctre_phoenix_Sensors_PigeonImuJNI
#define _Included_com_ctre_phoenix_Sensors_PigeonImuJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_new_PigeonImu_Talon
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1new_1PigeonImu_1Talon
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_new_PigeonImu
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1new_1PigeonImu
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_ConfigSetParameter
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1ConfigSetParameter
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_SetStatusFrameRateMs
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1SetStatusFrameRateMs
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_SetYaw
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1SetYaw
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_AddYaw
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1AddYaw
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_SetYawToCompass
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1SetYawToCompass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_SetFusedHeading
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1SetFusedHeading
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_AddFusedHeading
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1AddFusedHeading
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_SetFusedHeadingToCompass
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1SetFusedHeadingToCompass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_SetAccumZAngle
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1SetAccumZAngle
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_EnableTemperatureCompensation
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1EnableTemperatureCompensation
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_SetCompassDeclination
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1SetCompassDeclination
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_SetCompassAngle
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1SetCompassAngle
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_EnterCalibrationMode
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1EnterCalibrationMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetGeneralStatus
 * Signature: (JLjava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetGeneralStatus
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_Get6dQuaternion
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1Get6dQuaternion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetYawPitchRoll
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetYawPitchRoll
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetAccumGyro
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetAccumGyro
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetAbsoluteCompassHeading
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetAbsoluteCompassHeading
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetCompassHeading
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetCompassHeading
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetCompassFieldStrength
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetCompassFieldStrength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetTemp
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetTemp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetUpTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetUpTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetRawMagnetometer
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetRawMagnetometer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetBiasedMagnetometer
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetBiasedMagnetometer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetBiasedAccelerometer
 * Signature: (J)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetBiasedAccelerometer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetRawGyro
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetRawGyro
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetAccelerometerAngles
 * Signature: (J)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetAccelerometerAngles
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetFusedHeading
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetFusedHeading__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetFusedHeading
 * Signature: (JLjava/lang/Object;Ljava/lang/Object;)D
 */
JNIEXPORT jdouble JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetFusedHeading__JLjava_lang_Object_2Ljava_lang_Object_2
  (JNIEnv *, jclass, jlong, jobject, jobject);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetState
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetState
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetResetCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetResetCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetResetFlags
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetResetFlags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_GetFirmVers
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1GetFirmVers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    GetLastError
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_GetLastError
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ctre_phoenix_Sensors_PigeonImuJNI
 * Method:    JNI_HasResetOccured
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_ctre_phoenix_Sensors_PigeonImuJNI_JNI_1HasResetOccured
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
