/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ctre_phoenix_CANifierJNI */

#ifndef _Included_com_ctre_phoenix_CANifierJNI
#define _Included_com_ctre_phoenix_CANifierJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_ctre_phoenix_CANifierJNI
 * Method:    JNI_new_CANifier
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_ctre_phoenix_CANifierJNI_JNI_1new_1CANifier
  (JNIEnv *, jclass, jint);
/*
 * Class:     com_ctre_phoenix_CANifierJNI
 * Method:    JNI_SetLEDOutput
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_CANifierJNI_JNI_1SetLEDOutput
 (JNIEnv *, jclass, jlong handle, jint dutyCycle, jint ledChannel);
 /*
 * Class:     com_ctre_phoenix_CANifierJNI
 * Method:    JNI_SetGeneralOutputs
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_CANifierJNI_JNI_1SetGeneralOutputs
 (JNIEnv *, jclass, jlong handle, jint outputBits, jint isOutputBits);
 /*
 * Class:     com_ctre_phoenix_CANifierJNI
 * Method:    JNI_SetGeneralOutput
 * Signature: (JIBB)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_CANifierJNI_JNI_1SetGeneralOutput
 (JNIEnv *, jclass, jlong handle, jint outputPin, jboolean outputValue, jboolean outputEnable);
 /*
 * Class:     com_ctre_phoenix_CANifierJNI
 * Method:    JNI_SetPWMOutput
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_CANifierJNI_JNI_1SetPWMOutput
 (JNIEnv *, jclass, jlong handle, jint pwmChannel, jint dutyCycle);
 /*
 * Class:     com_ctre_phoenix_CANifierJNI
 * Method:    JNI_EnablePWMOutput
 * Signature: (JIB)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_CANifierJNI_JNI_1EnablePWMOutput
 (JNIEnv *, jclass, jlong handle, jint pwmChannel, jboolean bEnable);
 /*
 * Class:     com_ctre_phoenix_CANifierJNI
 * Method:    JNI_GetGeneralInputs
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_CANifierJNI_JNI_1GetGeneralInputs
 (JNIEnv *, jclass, jlong handle, jbooleanArray allPins);
 /*
 * Class:     com_ctre_phoenix_CANifierJNI
 * Method:    JNI_GetGeneralInput
 * Signature: (JI)B
 */
JNIEXPORT jboolean JNICALL Java_com_ctre_phoenix_CANifierJNI_JNI_1GetGeneralInput
 (JNIEnv *, jclass, jlong handle, jint inputPin);
 /*
 * Class:     com_ctre_phoenix_CANifierJNI
 * Method:    JNI_GetPWMInput
 * Signature: (JI)B
 */
JNIEXPORT void JNICALL Java_com_ctre_phoenix_CANifierJNI_JNI_1GetPWMInput
	 (JNIEnv * env, jclass, jlong handle, jint pwmChannel, jfloatArray dutyCycleAndPeriod);

 /*
 * Class:     com_ctre_phoenix_CANifierJNI
 * Method:    JNI_GetLastError
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ctre_phoenix_CANifierJNI_JNI_1GetLastError
 (JNIEnv *, jclass, jlong handle);
 /*
 * Class:     com_ctre_phoenix_CANifierJNI
 * Method:    JNI_GetBatteryVoltage
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_ctre_phoenix_CANifierJNI_JNI_1GetBatteryVoltage
 (JNIEnv *, jclass, jlong handle);
#ifdef __cplusplus
}
#endif
#endif
